version: "3.8"

services:
  db:
    image: postgres:13
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: "pass"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data
volumes:
  my_db_data:
