// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package scorecard_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func CreateScoreCard() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>Create Score Card</h1><section><form method=\"post\" hx-swap=\"transition:true\">Tee: <input type=\"text\" name=\"tee\" placeholder=\"Tee Name or Color\" required autofocus minlength=\"3\" maxlength=\"64\"> Par <input type=\"number\" name=\"par\" required autofocus min=\"60\" max=\"74\" placeholder=\"72\"> Slope: <input type=\"number\" name=\"slope\" required autofocus min=\"80\" max=\"150\" placeholder=\"120\"> Rating: <input type=\"number\" name=\"rating\" step=\"any\" required autofocus min=\"65.0\" max=\"80.0\" placeholder=\"71.0\"> Course ID: <input type=\"number\" name=\"courseId\" required autofocus min=\"1\" max=\"100\" placeholder=\"1\"><footer><button>Save</button> <a href=\"/course\">Cancel</a></footer></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
